### ISSUE TITLE
Error in Voyager 

### ISSUE THREAD

**Issue by kanitw** [uwdata/voyager#163]
I get the following error in the main voyager (without bower link)

```
Error: Drop Error: You must provide a target.
    at new DropInstance (http://localhost:3000/bower_components/drop/dist/js/drop.js:164:15)
    at new drop (http://localhost:3000/bower_components/drop/dist/js/drop.js:105:12)
    at postLink (http://localhost:3000/bower_components/vega-lite-ui/vlui.js:637:26)
    at http://localhost:3000/bower_components/angular/angular.js:8284:44
    at invokeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8290:9)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:7800:11)
    at http://localhost:3000/bower_components/angular/angular.js:8030:13
    at processQueue (http://localhost:3000/bower_components/angular/angular.js:13292:27)
    at http://localhost:3000/bower_components/angular/angular.js:13308:27
    at Scope.$get.Scope.$eval (http://localhost:3000/bower_components/angular/angular.js:14547:28) <div class="ng-isolate-scope">(anonymous function) @ angular.js:11699$get @ angular.js:8628invokeLinkFn @ angular.js:8292nodeLinkFn @ angular.js:7800(anonymous function) @ angular.js:8030processQueue @ angular.js:13292(anonymous function) @ angular.js:13308$get.Scope.$eval @ angular.js:14547$get.Scope.$digest @ angular.js:14363$get.Scope.$apply @ angular.js:14652done @ angular.js:9734completeRequest @ angular.js:9924requestLoaded @ angular.js:9865
2angular.js:11699 TypeError: element.scrollTop is not a function
    at updateFields (vislist.js:44)
    at Object.fn (vislist.js:53)
    at Scope.$get.Scope.$digest (angular.js:14389)
    at Scope.$get.Scope.$apply (angular.js:14652)
    at done (angular.js:9734)
    at completeRequest (angular.js:9924)
    at XMLHttpRequest.requestLoaded (angular.js:9865)
```

**Comment by domoritz** [comment]
Same issues in polestar. I think the problem is that we include angular before jquery.
